language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t japy/docker-react-test -f Dockerfile.dev .

script:
    - docker run -e CI=true japy/docker-react-test npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "crabi-onboarding-docker-react"
    env: "CrabiOnboardingDockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-243492006712"
    bucket_path: "crabi-onboarding-docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY